name: iot_smarthome
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  slide_to_act: ^2.0.2
  get: ^4.7.2
  firebase_core: ^4.1.1 
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_fonts: ^6.3.2
  smooth_page_indicator: ^1.2.1
  firebase_database: ^12.0.2
  animations: ^2.0.6
  kf_drawer: ^2.0.0
  image_picker: ^1.2.0
  sleek_circular_slider: ^2.1.0
  syncfusion_flutter_gauges: ^31.1.21
  syncfusion_flutter_charts: ^31.1.21
  flutter_staggered_grid_view: ^0.4.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_advanced_avatar: ^1.5.2
  convex_bottom_bar: ^3.2.0
  shared_preferences: ^2.5.3
  settings_ui: ^2.0.2
  file_picker: ^10.3.3
  flutter_tts: ^4.2.3
  http: ^1.5.0
  #kf_drawer: ^1.2.1
  uuid: ^4.5.1
  
  lottie: ^3.3.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.3.0
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  qr_flutter: ^4.1.0
  qr_code_tools: ^0.2.0
  image_gallery_saver_plus: ^4.0.1
  share_plus: ^7.0.1
  path_provider: ^2.1.1
  firebase_messaging: ^16.0.3
  flutter_slidable: ^4.0.3
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.2
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
  flutter_timer_countdown: ^1.0.7
  haptic_feedback: ^0.5.1
  awesome_notifications: ^0.10.1

dev_dependencies:
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/home.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - assets/lotties/Home.json
    - assets/lotties/smarthome.json
    - assets/lotties/voice.json
    - assets/lotties/recording.json
    - assets/lotties/fingerprinter.json
    - assets/images/banner_homepage.png

  fonts:
    - family: OpenSansCondensed
      fonts:
        - asset: assets/fonts/OpenSans_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans_Condensed-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans_Condensed-Medium.ttf
          weight: 600
        - asset: assets/fonts/OpenSans_Condensed-Bold.ttf 
          weight: 700
        - asset: assets/fonts/OpenSans_SemiCondensed-ExtraBold.ttf
          weight: 800



